export default {
  buyer: [],
  cart: [],
  products: [
    {
      'id': '1',
      'image': 'https://static01.nyt.com/images/2020/11/20/books/review/best-books-04/best-books-04-superJumbo.png?quality=90&auto=webp',
      'title': 'A Children’s Bible',
      'price': 25,
      'description': 'By Lydia Millet',
    },
    {
      'id': '2',
      'image': 'https://static01.nyt.com/images/2020/11/20/books/review/best-books-03/best-books-03-superJumbo.png?quality=90&auto=webp',
      'title': 'Deacon King Kong',
      'price': 28,
      'description': 'By James McBride',
    },
    {
      'id': '3',
      'image': 'https://static01.nyt.com/images/2020/11/20/books/review/best-books-05/best-books-05-superJumbo.png?quality=90&auto=webp',
      'title': 'Hamnet',
      'price': 26,
      'description': 'By Maggie O’Farrell',
    },
    {
      'id': '4',
      'image': 'https://static01.nyt.com/images/2020/11/20/books/review/best-books/best-books-superJumbo.png?quality=90&auto=webp',
      'title': 'Homeland Elegies',
      'price': 28,
      'description': 'By Ayad Akhtar',
    },
    {
      'id': '5',
      'image': 'https://static01.nyt.com/images/2020/05/27/books/best-books-bennett/26BOOKBENNETT1-superJumbo.jpg?quality=90&auto=webp',
      'title': 'The Vanishing Half',
      'price': 27,
      'description': 'By Brit Bennett',
    },
    {
      'id': '6',
      'image': 'https://static01.nyt.com/images/2020/04/01/books/best-books-kolker/best-books-kolker-superJumbo-v2.png?quality=90&auto=webp',
      'title': 'Hidden Valley Road',
      'price': 29,
      'description': 'By Robert Kolker',
    },
    {
      'id': '7',
      'image': 'https://static01.nyt.com/images/2020/11/17/books/review/best-books-obama/best-books-obama-superJumbo.png?quality=90&auto=webp',
      'title': 'A Promised Land',
      'price': 35,
      'description': 'By Barack Obama',
    },
    {
      'id': '8',
      'image': 'https://static01.nyt.com/images/2020/11/20/books/review/best-books-06/best-books-06-superJumbo.png?quality=90&auto=webp',
      'title': 'Shakespeare in a Divided America',
      'price': 27,
      'description': 'By James Shapiro',
    },
    {
      'id': '9',
      'image': 'https://static01.nyt.com/images/2020/11/20/books/review/best-books-07/best-books-07-superJumbo.png?quality=90&auto=webp',
      'title': 'Uncanny Valley',
      'price': 27,
      'description': 'By Anna Wiener',
    },
    {
      'id': '10',
      'image': 'https://static01.nyt.com/images/2020/11/20/books/review/best-books-02/best-books-02-superJumbo.png?quality=90&auto=webp',
      'title': 'War',
      'price': 30,
      'description': 'By Margaret MacMillan',
    },
  ],
};